EV simulator: Check the returned error of getNextLoad()
CamusEnergy/kinney pull request #35
Opened 2020-08-10 03:57 UTC by tzstoyanov

Check the returned error of getNextLoad() right after its call,
to avoid possible nil pointer exception.
https://github.com/CamusEnergy/kinney/issues/32

Reported-by: Diana Atanasova <dianaa@vmware.com>
Signed-off-by: Tzvetomir Stoyanov (VMware) <tz.stoyanov@gmail.com>

2020-08-25 14:09 UTC, difince requested changes

2020-08-25 14:09 UTC, difince commented on controller/chargepoint/simulator/sim/handlers.go
> +		resp.ResponseCode = "102"
In case that there is not err the responseCode should be 100

2020-09-03 18:09 UTC, difince approved these changes
LGTM

2020-09-03 18:18 UTC, difince commented on controller/chargepoint/simulator/sim/handlers.go
>  		resp.ResponseText = "No load recorded"
Do you think it is ok to overwrite the real err message ?

2020-09-08 08:46 UTC, merged

2020-09-08 09:20 UTC, tzstoyanov commented on controller/chargepoint/simulator/sim/handlers.go
>  		resp.ResponseText = "No load recorded"
Yes, we can keep the original error message. I'll review the error handling of the all APIs and will submit a patch to unify them.